<template>
  <div class="iq-banner">
    <p class="rs-p-wp-fix"></p>
    <rs-module-wrap id="rev_slider_8_1_wrapper" data-alias="xamin-behaviour" data-source="gallery" style="background:transparent;padding:0;margin:0px auto;margin-top:0;margin-bottom:0;">
      <rs-module id="rev_slider_8_1" style="display:none;" data-version="6.1.0">
        <rs-slides>
          <rs-slide data-key="rs-6" data-title="Slide" data-anim="ei:d;eo:d;s:1000;r:0;t:fade;sl:0;">
            <img :src="require('../../static/revslider/temp_rev_image/xamin-demo8-01.jpg')" title="xamin-demo8-01.jpg" width="1600" height="812" class="rev-slidebg" data-no-retina>
            <!--
              -->
            <h2
              id="slider-6-slide-6-layer-3" 
              class="rs-layer"
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:218px;y:b;yo:233px;"
              data-text="w:normal;s:80;l:90;fw:900;"
              data-frame_1="e:Power4.easeInOut;st:600;sp:1200;sR:600;"
              data-frame_1_sfx="se:blocktoright;"
              data-frame_999="o:0;st:w;sR:7200;"
              style="z-index:8;font-family:Lato;text-transform:uppercase;"
              >User 
            </h2>
            <!--
              -->
            <h1
              id="slider-6-slide-6-layer-4" 
              class="rs-layer"
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:214px;y:b;yo:128px;"
              data-text="w:normal;s:120;l:90;fw:900;"
              data-frame_1="e:Power4.easeInOut;st:600;sp:1200;sR:600;"
              data-frame_1_sfx="se:blocktoright;"
              data-frame_999="o:0;st:w;sR:7200;"
              style="z-index:9;font-family:Lato;text-transform:uppercase;"
              >Behaviour 
            </h1>
            <!--
              -->
            <h3
              id="slider-6-slide-6-layer-7" 
              class="rs-layer"
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:769px;y:b;yo:62px;"
              data-text="w:normal;s:30;l:50;fw:900;"
              data-frame_1="e:Power4.easeInOut;st:600;sp:1200;sR:600;"
              data-frame_1_sfx="se:blocktoright;"
              data-frame_999="o:0;st:w;sR:7200;"
              style="z-index:10;font-family:Lato;text-transform:uppercase;"
              >ANALYSIS 
            </h3>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-8" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:c;xo:-384px;y:c;yo:17px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:1900;sp:1000;sR:1900;"
              data-frame_999="o:0;st:w;sR:6100;"
              data-loop_0="o:0;"
              data-loop_999="sp:3000;e:Sine.easeInOut;yyf:t;"
              style="z-index:14;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-dom08-02.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-9" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:c;xo:101px;y:c;yo:17px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:1800;sp:1000;sR:1800;"
              data-frame_999="o:0;st:w;sR:6200;"
              data-loop_0="o:0;"
              data-loop_999="sp:5000;e:Sine.easeInOut;yyf:t;"
              style="z-index:13;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-dom08-02.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-10" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:209px;y:b;yo:209px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:1700;sp:1000;sR:1700;"
              data-frame_999="o:0;st:w;sR:6300;"
              data-loop_0="o:0;"
              data-loop_999="sp:1500;e:Sine.easeInOut;yyf:t;"
              style="z-index:12;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-dom08-02.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-11" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:c;xo:-84px;y:c;yo:121px;"
              data-text="w:normal;"
              data-dim="w:44px;h:44px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2100;sp:1000;sR:2100;"
              data-frame_999="o:0;st:w;sR:5900;"
              data-loop_0="o:0;"
              data-loop_999="sp:1500;e:Sine.easeInOut;yyf:t;"
              style="z-index:16;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-03.png')" width="44" height="44" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-12" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:c;xo:389px;y:c;yo:121px;"
              data-text="w:normal;"
              data-dim="w:44px;h:44px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2000;sp:1000;sR:2000;"
              data-frame_999="o:0;st:w;sR:6000;"
              data-loop_0="o:0;"
              data-loop_999="sp:4000;e:Sine.easeInOut;yyf:t;"
              style="z-index:15;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-03.png')" width="44" height="44" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-13" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:107px;y:241px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:1600;sp:1000;sR:1600;"
              data-frame_999="o:0;st:w;sR:6400;"
              data-loop_0="o:0;"
              data-loop_999="sp:8000;e:Sine.easeInOut;yyf:t;"
              style="z-index:11;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-dom08-02.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-14" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:c;xo:204px;y:c;yo:116px;"
              data-text="w:normal;"
              data-dim="w:76px;h:76px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2200;sp:1000;sR:2200;"
              data-frame_999="o:0;st:w;sR:5800;"
              data-loop_0="o:0;"
              data-loop_999="sp:1500;e:Sine.easeInOut;yyf:t;"
              style="z-index:17;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-04.png')" width="76" height="76" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-15" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:203px;y:c;yo:121px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2400;sp:1000;sR:2400;"
              data-frame_999="o:0;st:w;sR:5600;"
              data-loop_0="o:0;"
              data-loop_999="sp:7000;e:Sine.easeInOut;yyf:t;"
              style="z-index:19;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-05.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-16" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:492px;y:c;yo:-87px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.9;sY:0.9;"
              data-frame_1="st:2300;sp:1000;sR:2300;"
              data-frame_999="o:0;st:w;sR:5700;"
              data-loop_0="o:0;"
              data-loop_999="sp:2000;e:Sine.easeInOut;yyf:t;"
              style="z-index:18;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-05.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-17" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:1243px;y:210px;"
              data-text="w:normal;"
              data-dim="w:76px;h:76px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2500;sp:1000;sR:2500;"
              data-frame_999="o:0;st:w;sR:5500;"
              data-loop_0="o:0;"
              data-loop_999="sp:10000;e:Sine.easeInOut;yyf:t;"
              style="z-index:20;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-07.png')" width="76" height="76" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-18" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:396px;y:241px;"
              data-text="w:normal;"
              data-dim="w:28px;h:28px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2600;sp:1000;sR:2600;"
              data-frame_999="o:0;st:w;sR:5400;"
              data-loop_0="o:0;"
              data-loop_999="sp:5000;e:Sine.easeInOut;yyf:t;"
              style="z-index:21;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-06.png')" width="28" height="28" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-20" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:c;xo:-91px;y:c;yo:11px;"
              data-text="w:normal;"
              data-dim="w:264px;h:264px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2700;sp:1000;sR:2700;"
              data-frame_999="o:0;st:w;sR:5300;"
              data-loop_999="rZ:360;sp:30000;"
              style="z-index:22;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-08.png')" width="264" height="264" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-21" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:-13px;y:c;yo:120px;"
              data-text="w:normal;"
              data-dim="w:264px;h:264px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2800;sp:1000;sR:2800;"
              data-frame_999="o:0;st:w;sR:5200;"
              data-loop_999="rZ:360;sp:30000;"
              style="z-index:24;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-09.png')" width="264" height="264" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-22" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:r;xo:112px;y:c;yo:-3px;"
              data-text="w:normal;"
              data-dim="w:196px;h:184px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2900;sp:1000;sR:2900;"
              data-frame_999="o:0;st:w;sR:5100;"
              style="z-index:26;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-10.png')" width="196" height="184" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-23" 
              data-type="image"
              data-rsp_ch="on"
              data-xy="x:701px;y:259px;"
              data-text="w:normal;"
              data-dim="w:226px;h:184px;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:3010;sp:1000;sR:3010;"
              data-frame_999="o:0;st:w;sR:4990;"
              style="z-index:27;font-family:Roboto;"
              ><img :src="require('../../static/revslider/temp_rev_image/xamin-d8-12.png')" width="226" height="184" data-no-retina> 
            </rs-layer>
            <!--
              -->
            <h5
              id="slider-6-slide-6-layer-24" 
              class="rs-layer"
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:743px;y:271px;"
              data-text="w:normal;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:3200;sp:1000;sR:3200;"
              data-frame_999="o:0;st:w;sR:4800;"
              style="z-index:29;font-family:Roboto;"
              >Measuring  For  
            </h5>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-25" 
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:r;xo:159px;y:c;yo:-71px;"
              data-text="w:normal;"
              data-frame_0="sX:0.9;sY:0.9;"
              data-frame_1="st:3100;sp:1000;sR:3100;"
              data-frame_999="o:0;st:w;sR:4900;"
              style="z-index:28;font-family:Roboto;"
              >Identify 
            </rs-layer>
            <!--
              -->
            <h4
              id="slider-6-slide-6-layer-26" 
              class="rs-layer"
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:c;xo:-9px;y:c;yo:-134px;"
              data-text="w:normal;s:28;l:38;fw:700;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:3400;sp:1000;sR:3400;"
              data-frame_999="o:0;st:w;sR:4600;"
              style="z-index:31;font-family:Lato;"
              >Success 
            </h4>
            <!--
              -->
            <h4
              id="slider-6-slide-6-layer-27" 
              class="rs-layer"
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:r;xo:157px;y:c;yo:-38px;"
              data-text="w:normal;s:28;l:38;fw:700;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:3300;sp:1000;sR:3300;"
              data-frame_999="o:0;st:w;sR:4700;"
              style="z-index:30;font-family:Lato;"
              >Problems 
            </h4>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-31" 
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:-42px;y:245px;"
              data-text="w:normal;"
              data-btrans="rZ:-90;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:3600;sp:1000;sR:3600;"
              data-frame_999="o:0;st:w;sR:4400;"
              style="z-index:33;font-family:Roboto;text-transform:capitalize;"
              >#Iqonic Design 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-32" 
              data-type="text"
              data-color="#253b5c"
              data-rsp_ch="on"
              data-xy="x:r;xo:-50px;y:b;yo:86px;"
              data-text="w:normal;"
              data-btrans="rZ:-90;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:3500;sp:1000;sR:3500;"
              data-frame_999="o:0;st:w;sR:4500;"
              style="z-index:32;font-family:Roboto;text-transform:capitalize;"
              >#Design Inspiration 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-33" 
              data-type="text"
              data-color="#ffffff"
              data-rsp_ch="on"
              data-xy="x:1465px;y:554px;"
              data-text="w:normal;s:30;l:30;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2800;sp:1000;"
              data-frame_999="o:0;st:w;sR:5900;"
              style="z-index:25;font-family:Roboto;"
              ><span class="timer" data-to="49" data-speed="5000">49</span> 
            </rs-layer>
            <!--
              -->
            <rs-layer
              id="slider-6-slide-6-layer-34" 
              data-type="text"
              data-color="#ffffff"
              data-rsp_ch="on"
              data-xy="x:694px;y:445px;"
              data-text="w:normal;s:30;l:30;"
              data-frame_0="sX:0.8;sY:0.8;"
              data-frame_1="e:Power4.easeOut;st:2700;sp:1000;sR:2700;"
              data-frame_999="o:0;st:w;sR:5300;"
              style="z-index:23;font-family:Roboto;"
              ><span class="timer" data-to="59" data-speed="5000">59</span> 
            </rs-layer>
            <!--
              -->						
          </rs-slide>
        </rs-slides>
        <rs-progress class="rs-bottom" style="visibility: hidden !important;"></rs-progress>
      </rs-module>
    </rs-module-wrap>
  </div>
</template>
<script>
export default {
  name : 'Home'  
}
</script>
