<template>
  <rs-module-wrap id="rev_slider_3_1_wrapper" data-alias="Data-Center" data-source="gallery" style="background:transparent;padding:0;margin:0px auto;margin-top:0;margin-bottom:0;">
    <rs-module id="rev_slider_3_1" class=" rs-ov-hidden" style="display:none;" data-version="6.1.0">
      <rs-slides>
        <rs-slide data-key="rs-3" data-title="Slide" data-anim="ei:d,d,d,d,d,d,d,d,d;eo:d,d,d,d,d,d,d,d,d;s:1000ms,d,d,d,d,d,d,d,d;r:0,0,0,0,0,0,0,0,0;t:fade,grayscale,blurlight,blurstrong,fade,crossfade,fadethroughlight,fadethroughdark,fadethroughtransparent;sl:d,d,d,d,d,d,d,d,d;" data-firstanim="t:fade;sl:12;">
          <img
            alt="#"
            :src="require('../../static/revslider/assets/dummy.png')"
            title="data-c-b1.jpg"
            width="1600"
            height="874"
            data-lazyload="revslider/assets/data-c-b1.jpg"
            data-bg="f:100% 100%;"
            data-parallax="2"
            class="rev-slidebg"
            data-no-retina
          >
<!--
                            --><h2
                                id="slider-3-slide-3-layer-1"
                                class="rs-layer"
                                data-type="text"
                                data-color="#313e5b"
                                data-rsp_ch="on"
                                data-xy="x:l,l,l,c;xo:70px,70px,37px,-1px;yo:275px,275px,55px,34px;"
                                data-text="s:70,70,42,28;l:80,80,56,42;fw:900;a:inherit,inherit,inherit,center;"
                                data-dim="w:auto,auto,681px,681px;"
                                data-layeronlimit="on"
                                data-frame_0="y:-50;"
                                data-frame_1="st:600;sp:1000;sR:600;"
                                data-frame_999="o:0;tp:600;st:w;sR:7400;"
                                style="z-index:9;font-family:Lato;text-transform:capitalize;"
                            >
Data Center <br>
Analytics
          </h2><!--

                            --><p
                                id="slider-3-slide-3-layer-3"
                                class="rs-layer"
                                data-type="text"
                                data-color="#525f81"
                                data-rsp_ch="on"
                                data-xy="x:l,l,l,c;xo:71px,71px,40px,5px;y:m;yo:48px,48px,-183px,-150px;"
                                data-text="s:16,16,18,13;l:30,30,30,22;a:inherit,inherit,inherit,center;"
                                data-frame_0="y:-50;"
                                data-frame_1="st:900;sp:1000;sR:900;"
                                data-frame_999="o:0;tp:600;st:w;sR:7100;"
                                style="z-index:10;font-family:Karla;"
                            >
It is a long established fact that a reader will be distracted by the <br>readable content of a page when looking at its layout.
          </p><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-12"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="x:r;xo:-326px,-326px,-178px,-111px;yo:-75px,-75px,-40px,-24px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:1099px,1099px,601px,375px;h:1103px,1103px,603px,376px;"
                                data-frame_999="o:0;st:w;sR:8700;"
                                style="z-index:8;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="1099"
height="1103"
data-lazyload="revslider/assets/data-c-ellipse.png"
data-no-retina
>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-13"
                                class="button blue-btn rev-btn"
                                data-type="button"
                                data-rsp_ch="on"
                                data-xy="xo:73px,73px,39px,566px;yo:556px,556px,304px,187px;"
                                data-text="w:normal;s:16,16,8,10;l:30,30,15,22;"
                                data-dim="minh:0px,0px,none,none;"
                                data-padding="t:10,10,5,3;r:30,30,16,10;b:10,10,5,3;l:30,30,16,10;"
                                data-border="bor:50px,50px,50px,50px;"
                                data-frame_1="st:1180;sR:1180;"
                                data-frame_999="o:0;st:w;sR:7520;"
                                data-frame_hover="bgc:#313e5b;bor:50px,50px,50px,50px;sp:200;e:Power1.easeInOut;"
                                style="z-index:17;background-color:#437eeb;font-family:Lato;"
                            >
Read More
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-17"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="x:c;xo:277px,277px,151px,94px;y:m;yo:-105px,-105px,-56px,-34px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:192px,192px,104px,64px;h:168px,168px,91px,56px;"
                                data-frame_0="sX:0.9;sY:0.9;"
                                data-frame_1="st:4160;sp:1000;sR:4160;"
                                data-frame_999="o:0;st:w;sR:3840;"
                                style="z-index:18;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="247"
height="216"
data-lazyload="revslider/assets/cloud-data.png"
data-no-retina
>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-25"
                                class="rs-pxl-1"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="xo:1260px,1260px,549px,353px;yo:154px,154px,331px,280px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:151px,151px,112px,77px;h:102px,102px,112px,77px;"
                                data-frame_0="sX:0.9;sY:0.9;"
                                data-frame_1="st:2100;sp:1000;sR:2100;"
                                data-frame_999="o:0;st:w;sR:5900;"
                                data-tloop="u:true;"
                                data-loop_999="sX:0.8;sY:0.8;o:0.6;sp:2000;e:Power2.easeInOut;yys:t;yyf:t;"
                                style="z-index:13;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="364"
height="246"
data-lazyload="revslider/assets/2.png"
data-no-retina
>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-28"
                                data-type="text"
                                data-rsp_ch="on"
                                data-xy="xo:227px,227px,40px,174px;yo:568px,568px,274px,210px;"
                                data-text="w:normal;s:16,16,18,17;l:25,25,13,13;"
                                data-dim="h:auto,auto,auto,17px;"
                                data-frame_0="x:0,0,0,0px;y:-50,-50,-26,-24px;"
                                data-frame_1="x:0,0,0,0px;y:0,0,0,0px;st:1500;sp:1000;sR:1500;"
                                data-frame_999="o:0;st:w;sR:6500;"
                                style="z-index:11;font-family:Roboto;"
                            >
<a class="button_link iq-video popup-youtube" href="#"><i class="fas fa fa-play" />Watch Video</a>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-29"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="xo:856px,856px,184px,36px;yo:118px,118px,362px,271px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:552px,552px,470px,429px;h:489px,489px,387px,353px;"
                                data-frame_0="sX:0.9;sY:0.9;"
                                data-frame_1="st:1800;sp:930;sR:1800;"
                                data-frame_999="o:0;st:w;sR:6270;"
                                style="z-index:12;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="651"
height="577"
data-lazyload="revslider/assets/hgjmnhmgh.png"
data-no-retina
>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-30"
                                class="rs-pxl-1"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="xo:718px,718px,118px,0;yo:393px,393px,539px,461px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:101px,101px,54px,69px;h:58px,58px,31px,40px;"
                                data-frame_0="sX:0.9;sY:0.9;"
                                data-frame_1="st:2700;sp:1000;sR:2700;"
                                data-frame_999="o:0;st:w;sR:5300;"
                                data-tloop="u:true;"
                                data-loop_999="sX:0.8;sY:0.8;o:0.6;sp:2000;e:Power2.easeInOut;yys:t;yyf:t;"
                                style="z-index:14;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="261"
height="151"
data-lazyload="revslider/assets/6.png"
data-no-retina
>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-31"
                                class="rs-pxl-2"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="xo:748px,748px,169px,81px;yo:565px,565px,649px,531px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:131px,131px,71px,64px;h:99px,99px,53px,48px;"
                                data-frame_0="sX:0.9;sY:0.9;"
                                data-frame_1="st:3000;sp:1000;sR:3000;"
                                data-frame_999="o:0;st:w;sR:5000;"
                                data-loop_999="sX:1.2;sY:1.2;o:0.6;sp:2000;st:1000;e:Power0.easeInOut;yys:t;yyf:t;"
                                style="z-index:15;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="387"
height="292"
data-lazyload="revslider/assets/3.png"
data-no-retina
>
          </rs-layer><!--

                            --><rs-layer
                                id="slider-3-slide-3-layer-32"
                                class="rs-pxl-1"
                                data-type="image"
                                data-rsp_ch="on"
                                data-xy="xo:1052px,1052px,380px,245px;yo:635px,635px,703px,555px;"
                                data-text="w:normal;s:20,20,10,6;l:0,0,13,8;"
                                data-dim="w:87px,87px,47px,70px;h:52px,52px,28px,41px;"
                                data-frame_0="y:-50,-50,-26,-16;"
                                data-frame_1="st:3300;sp:1000;sR:3300;"
                                data-frame_999="o:0;st:w;sR:4700;"
                                data-tloop="u:true;"
                                data-loop_999="sX:0.8;sY:0.8;o:0.6;sp:2000;e:Power2.easeInOut;yys:t;yyf:t;"
                                style="z-index:16;font-family:Roboto;"
                            >
<img
alt="#"
:src="require('../../static/revslider/assets/dummy.png')"
width="206"
height="122"
data-lazyload="revslider/assets/5.png"
data-no-retina
>
          </rs-layer><!--
-->
        </rs-slide>
      </rs-slides>
      <rs-static-layers>
        <!--
                    -->
      </rs-static-layers>
      <rs-progress class="rs-bottom" style="visibility: hidden !important;" />
    </rs-module>
  </rs-module-wrap>
</template>
<script>
export default {
  name: 'Home'
}
</script>
